### ISSUE TITLE
when try to install throw this error

### ISSUE THREAD

**Issue by AMarinaG** [contribution-jhipster-uga/generator-jhipster-stripe-payment#1]
TypeError: this.getJhipsterAppConfig is not a function
    at module.exports.readConfig (/usr/local/lib/node_modules/generator-jhipster-stripe-payment/generators/app/index.js:18:47)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:424:27)
    at /usr/local/lib/node_modules/generator-jhipster/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/generator-jhipster/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:425:13)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

**Comment by trane77** [comment]
I've just installed the package from npm, it doesn't include the fix yet!
